spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/your_database
    username: root
    password: mysql

  # JPA ??
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
    show-sql: true

  # Redis ??
  data:
    redis:
      host: localhost
      port: 6379

# JWT ??
jwt:
  secret: ${JWT_SECRET_KEY} # ????? ?? ??
  access-token-expiration: 1800000  # 30? (???)
  refresh-token-expiration: 604800000 # 7? (???)
